runtime: nodejs18

instance_class: F2

env_variables:
  NODE_ENV: production

handlers:
  - url: /static
    static_dir: picplate-frontend/build/static

  - url: /privacy-policy.html
    static_files: picplate-frontend/build/privacy-policy.html
    upload: picplate-frontend/build/privacy-policy.html

  - url: /.*
    static_files: picplate-frontend/build/index.html
    upload: picplate-frontend/build/index.html
