runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: production

handlers:
  # Send API requests to backend server (Express)
  - url: /api/.*
    script: auto

  # Static frontend files
  - url: /static
    static_dir: picplate-frontend/build/static

  - url: /privacy-policy.html
    static_files: picplate-frontend/build/privacy-policy.html
    upload: picplate-frontend/build/privacy-policy.html

  # All other frontend routes
  - url: /.*
    static_files: picplate-frontend/build/index.html
    upload: picplate-frontend/build/index.html
